In [1]:
import pandas as pd
import gc
import numpy as np
import os
from transformers import AutoTokenizer, AutoModelForTokenClassification
import torch
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import accuracy_score, f1_score
from tqdm import tqdm

pd.set_option('max_columns', 300)

In [2]:
output_labels = ['O', 'B-Lead', 'I-Lead', 'B-Position', 'I-Position', 'B-Claim', 'I-Claim',
                 'B-Counterclaim', 'I-Counterclaim', 'B-Rebuttal', 'I-Rebuttal',
                 'B-Evidence', 'I-Evidence', 'B-Concluding', 'I-Concluding']

replace_labels = {'O': 'O', 'B-Lead': 'Lead', 'I-Lead': 'Lead', 'B-Position': 'Position', 'I-Position': 'Position', 
                  'B-Claim': 'Claim', 'I-Claim': 'Claim', 'B-Counterclaim': 'Counterclaim', 'I-Counterclaim': 'Counterclaim', 
                  'B-Rebuttal': 'Rebuttal', 'I-Rebuttal': 'Rebuttal', 'B-Evidence': 'Evidence', 'I-Evidence': 'Evidence', 
                  'B-Concluding': 'Concluding Statement', 'I-Concluding': 'Concluding Statement'}

num_labels = len(output_labels)
key2val = {k: v for v, k in enumerate(output_labels)}
val2key = {v: k for v, k in enumerate(output_labels)}
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
def read_data(path):
    df = pd.DataFrame()
    id_list, text_list = [], []
    for filename in os.listdir(path):
        id_list.append(filename.split('.')[0])
        with open(f'{path}/{filename}') as file:
            text_list.append(file.read())
    df['id'] = id_list
    df['text'] = text_list
    return df


def create_entities(df, df_labels):
    df['entities'] = ''
    for i in range(len(df)):
        current_num_words = len(df.loc[i, 'text'].split())
        file_id = df.loc[i, 'id']
        pos_character_start_list = df_labels.loc[df_labels['id'] == file_id, 'discourse_start'].astype('int').tolist()
        pos_character_end_list = df_labels.loc[df_labels['id'] == file_id, 'discourse_end'].astype('int').tolist()
        labels_list = df_labels.loc[df_labels['id'] == file_id, 'discourse_type'].tolist()
        entities = ['O' for _ in range(len(df.loc[i, 'text'].split()))]
        
        for j in range(len(labels_list)):
            pos_character_start, pos_character_end = pos_character_start_list[j], pos_character_end_list[j]
            pos_word_start = len(df.loc[i, 'text'][:pos_character_start].split())
            pos_word_end = len(df.loc[i, 'text'][:pos_character_end].split()) - 1
            for k in range(pos_word_start, pos_word_end):
                if k == pos_word_start:
                    entities[k] = f'B-{labels_list[j].split()[0]}'
                else:
                    entities[k] = f'I-{labels_list[j].split()[0]}'
        df.loc[i, 'entities'] = ' '.join(entities)

    return df


def text_f1(labels, preds, word_ids):
    arr_length = 0
    active_preds = dict()
    active_labels = dict()
    
    for i in range(len(preds)):
        active_preds[i] = []
        active_labels[i] = []
        last_word_id = -100
        for j in range(len(preds[i])):
            #print(f'label: {labels[i][j]} pred: {preds[i][j]}')
            current_word_id = word_ids[i][j]
            if labels[i][j] != -100 and current_word_id != last_word_id:
                active_preds[i].append(preds[i][j])
                active_labels[i].append(labels[i][j])
                arr_length += 1
            last_word_id = current_word_id

    metric_preds = np.zeros(arr_length)
    metric_labels = np.zeros(arr_length)
    current_pos = 0
    for i in range(len(active_preds)):
        for j in range(len(active_preds[i])):
            metric_preds[current_pos] = active_preds[i][j]
            metric_labels[current_pos] = active_labels[i][j]
            current_pos += 1
    
    return f1_score(metric_labels, metric_preds, average='weighted')


def preds2submission(preds, file_id_list, word_ids):
    id_list, label_list, predictionstring_list = [], [], []
    for i in range(len(preds)):
        last_label = 'O'
        words_count = 0
        predictionstring = ''
        last_word_id = -100
        is_not_finished = True
        for j in range(len(preds[i])):
            current_label = replace_labels[val2key[preds[i][j]]]
            current_word_id = word_ids[i][j]
            #print(f'cur_word_id: {current_word_id} last_word_id: {last_word_id} cur_label: {current_label} last_label: {last_label} i: {i} j: {j}')
            if current_word_id == -100 or current_word_id == last_word_id:
                #print('Continue')
                
                if current_word_id == -100 and j > 0 and last_label != 'O' and is_not_finished:
                    id_list.append(file_id_list[i])
                    label_list.append(last_label)
                    predictionstring_list.append(predictionstring)
                    is_not_finished = False
                
                continue
            if current_label != last_label:
                if last_label != 'O':
                    id_list.append(file_id_list[i])
                    label_list.append(last_label)
                    predictionstring_list.append(predictionstring)
                    
                    if current_label != 'O':
                        predictionstring = str(words_count)
                else:
                    predictionstring = str(words_count)
            elif current_label == last_label and current_label != 'O':
                predictionstring += f' {words_count}'
            
            """if j == len(preds[i]) - 1 and current_label != 'O':
                id_list.append(file_id_list[i])
                label_list.append(current_label)
                predictionstring_list.append(predictionstring)"""
                
            last_word_id = current_word_id
            last_label = current_label
            words_count += 1

    print(f'id: {len(id_list)}')
    print(f'class: {len(label_list)}')
    print(f'pred: {len(predictionstring_list)}')
    df = pd.DataFrame({'id': id_list, 'class': label_list, 'predictionstring': predictionstring_list})
    return df

In [4]:
class TextDataset(Dataset):
    def __init__(self, data, tokenizer, max_length, is_label=False):
        self.text = data['text']
        self.entities = data['entities'] if is_label else None
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.is_label = is_label

    def __len__(self):
        return len(self.text)

    def __getitem__(self, index):
        encoding = self.tokenizer(self.text[index].split(), is_split_into_words=True, truncation=True,
                                  padding='max_length', max_length=self.max_length)
        word_ids = encoding.word_ids()
        return_word_ids = []

        if self.is_label:
            entities_list = self.entities[index].split()
        labels = []
        for word_id in word_ids:
            if word_id is None:
                return_word_ids.append(-100)
                if self.is_label:
                    labels.append(-100)
            else:
                return_word_ids.append(word_id)
                if self.is_label:
                    labels.append(key2val[entities_list[word_id]])
        
        if self.is_label:
            encoding['labels'] = labels

        item = {key: torch.as_tensor(val) for key, val in encoding.items()}

        return item, np.array(return_word_ids)


class TextModel:
    def __init__(self, model_name, max_length):
        self.model_name = model_name
        self.num_folds = 3
        self.tokenizer = None
        self.max_length = max_length

    def fit(self, data, batch_size=4, lr=[2.5e-5, 2.5e-5, 2.5e-6, 2.5e-6, 2.5e-7], epochs=5, num_folds=1):
        
        self.num_folds = num_folds
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name, add_prefix_space=True)

        full_preds = np.zeros((len(data), self.max_length))
        full_labels = np.zeros((len(data), self.max_length))

        kfold = KFold(n_splits=10, shuffle=True, random_state=0)
        current_fold = 0
        for fold, (trn_ind, val_ind) in enumerate(kfold.split(data)):
            
            if fold not in [0]:
                continue
            
            data_train = data.loc[trn_ind]
            data_train.index = range(len(data_train))
            data_val = data.loc[val_ind]
            data_val.index = range(len(data_val))

            dataset_train = TextDataset(data_train, self.tokenizer, max_length=self.max_length, is_label=True)
            loader_train = DataLoader(dataset=dataset_train, batch_size=batch_size, shuffle=False, pin_memory=True)

            dataset_val = TextDataset(data_val, self.tokenizer, max_length=self.max_length, is_label=True)
            loader_val = DataLoader(dataset=dataset_val, batch_size=batch_size, shuffle=False, pin_memory=True)

            model = AutoModelForTokenClassification.from_pretrained(self.model_name, num_labels=num_labels).to(device)
            
            optimizer = optim.Adam(params=model.parameters(), lr=lr[0])
            #scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.1)

            for epoch in range(epochs):
                print(f'epoch: {epoch+1}')
                model.train()
                for batch, _ in tqdm(loader_train):
                    input_ids = batch['input_ids'].to(device)
                    attention_mask = batch['attention_mask'].to(device)
                    labels = batch['labels'].to(device)
                    
                    for g in optimizer.param_groups:
                        g['lr'] = lr[epoch]

                    loss, _ = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels, return_dict=False)
                    
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

                with torch.no_grad():
                    model.eval()
                    current_pos = 0
                    temp_preds = np.zeros((len(data_val), self.max_length))
                    temp_labels = np.zeros((len(data_val), self.max_length))
                    temp_words = np.zeros((len(data), self.max_length))
                    for batch, word_ids in tqdm(loader_val):
                        input_ids = batch['input_ids'].to(device)
                        attention_mask = batch['attention_mask'].to(device)
                        labels = batch['labels'].to(device)
                        current_batch_size = len(batch['input_ids'])

                        _, logit_preds = model(input_ids=input_ids, attention_mask=attention_mask,
                                               labels=labels, return_dict=False)
                        flattened_preds = torch.argmax(logit_preds.view(-1, model.num_labels), dim=1)
                        temp_preds[current_pos:current_pos+current_batch_size] = flattened_preds.view(current_batch_size, -1).cpu().numpy()
                        temp_labels[current_pos:current_pos+current_batch_size] = labels.cpu().numpy()
                        temp_words[current_pos:current_pos+current_batch_size] = word_ids
                        current_pos += current_batch_size
                    full_preds[val_ind] = temp_preds
                    full_labels[val_ind] = temp_labels
                    
                    print(f'f1_score: {text_f1(temp_labels, temp_preds, temp_words)} fold: {current_fold}')
                
                #scheduler.step()
            
            torch.cuda.empty_cache()
            gc.collect()
            torch.save(model.state_dict(), f'./{self.model_name.split("/")[-1]}{current_fold+1}.pt')
            current_fold += 1

        print(f'full_preds: {full_preds} shape: {full_preds.shape}')

        return full_preds, full_labels
    
    def predict(self, data, batch_size=4, is_label=False):
        dataset = TextDataset(data, self.tokenizer, max_length=self.max_length, is_label=is_label)
        loader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=False, pin_memory=True)
        
        preds = np.zeros((len(data), self.max_length, num_labels))
        labels = np.zeros((len(data), self.max_length))
        words = np.zeros((len(data), self.max_length))
        
        with torch.no_grad():
            for fold in range(self.num_folds):
                model = AutoModelForTokenClassification.from_pretrained(self.model_name, num_labels=num_labels).to(device)
                model.load_state_dict(torch.load(f'./{self.model_name.split("/")[-1]}{fold+1}.pt'))
                model.eval()
                current_pos = 0
                for batch, word_ids in tqdm(loader):
                    input_ids = batch['input_ids'].to(device)
                    attention_mask = batch['attention_mask'].to(device)
                    labels_temp = None
                    current_batch_size = len(batch['input_ids'])
                    if is_label:
                        labels_temp = batch['labels'].to(device)
                        _, logit_preds = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels_temp, return_dict=False)
                        labels[current_pos:current_pos+batch_size] = labels_temp.cpu().numpy()
                    else:
                        logit_preds = model(input_ids=input_ids, attention_mask=attention_mask, return_dict=False)[0]
                    #print(f'\nwids: {word_ids} \nwids_len: {len(word_ids)} \nwords: {words} \nwords_len: {len(words)}')
                    #print(f'w_ids_shape: {word_ids.shape} words_shape: {words.shape} words_batch_shape: {words[current_pos:current_pos+current_batch_size].shape}')
                    preds[current_pos:current_pos+current_batch_size] += logit_preds.cpu().numpy()
                    words[current_pos:current_pos+current_batch_size] = word_ids
                    current_pos += current_batch_size
        preds = preds / self.num_folds
        return np.argmax(preds, axis=2), labels, words

In [5]:
df_labels = pd.read_csv('../input/feedback-prize-2021/train.csv')
df_train = read_data('../input/feedback-prize-2021/train')

#df_train, df_val = train_test_split(df_train, test_size=0.2, shuffle=True, random_state=0)

df_train.index = range(len(df_train))
df_train = create_entities(df_train, df_labels)

#df_val.index = range(len(df_val))
#df_val = create_entities(df_val, df_labels)

df_test = read_data('../input/feedback-prize-2021/test')

model = TextModel(model_name='../input/huggingfacebigbirdrobertabase', max_length=1024)
#model = TextModel(model_name='../input/py-bigbird-v26', max_length=1024)
val_preds, val_labels = model.fit(df_train)
#preds, labels, word_ids = model.predict(df_val, is_label=True)
test_preds, _, test_word_ids = model.predict(df_test)

normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Some weights of the model checkpoint at ../input/huggingfacebigbirdrobertabase were not used when initializing BigBirdForTokenClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BigBirdForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BigBirdForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model 

epoch: 1


  0%|          | 0/3509 [00:00<?, ?it/s]/opt/conda/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /usr/local/src/pytorch/aten/src/ATen/native/BinaryOps.cpp:461.)
  return torch.floor_divide(self, other)
100%|██████████| 390/390 [01:44<00:00,  3.72it/s]


f1_score: 0.7625139235728716 fold: 0
epoch: 2


100%|██████████| 390/390 [01:44<00:00,  3.74it/s]


f1_score: 0.7697419510132478 fold: 0
epoch: 3


100%|██████████| 390/390 [01:44<00:00,  3.72it/s]


f1_score: 0.7805343580703379 fold: 0
epoch: 4


100%|██████████| 390/390 [01:44<00:00,  3.74it/s]


f1_score: 0.7805882612349312 fold: 0
epoch: 5


100%|██████████| 390/390 [01:44<00:00,  3.73it/s]


f1_score: 0.7812427660791504 fold: 0
full_preds: [[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 2.  1.  2. ... 12. 12. 12.]] shape: (15594, 1024)


Some weights of the model checkpoint at ../input/huggingfacebigbirdrobertabase were not used when initializing BigBirdForTokenClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BigBirdForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BigBirdForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BigBirdForTokenClassificat

In [6]:
#text_f1(labels, preds, word_ids)

In [7]:
submission_df = preds2submission(test_preds, df_test['id'], test_word_ids)
submission_df

id: 75
class: 75
pred: 75


id                 class  \
0   0FB0700DAF44                  Lead   
1   0FB0700DAF44              Position   
2   0FB0700DAF44                 Claim   
3   0FB0700DAF44                 Claim   
4   0FB0700DAF44                 Claim   
..           ...                   ...   
70  D46BCB48440A                 Claim   
71  D46BCB48440A              Evidence   
72  D46BCB48440A              Evidence   
73  D46BCB48440A              Evidence   
74  D46BCB48440A  Concluding Statement   

                                     predictionstring  
0   0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18...  
1                                   41 42 43 44 45 46  
2        49 50 51 52 53 54 55 56 57 58 59 60 61 62 63  
3   66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 8...  
4   84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 9...  
..                                                ...  
70                                                 44  
71  56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 7...  
72  150 151 152 153 154 155 156 157 158 159 160 16...  
73  223 224 225 226 227 228 229 230 231 232 233 23...  
74  306 307 308 309 310 311 312 313 314 315 316 31...  

[75 rows x 3 columns]

In [8]:
submission_df.to_csv('submission.csv', index=False)